[package]
name = "buteo-server"
version = "0.8.0"
edition = "2021"


[dependencies]
futures = "^0.3"
log = "0.4.20"
tokio = {version="1.36.0", features=["full"]}
async-tungstenite = {version="0.23", features=["tokio-runtime"]}
serde_json = "1.0.113"
serde = {version="1.0.196", features=["derive"]}
